name: Django CI

on:
  push:
    branches: [ workflow-test ]
  pull_request:
    branches: [ master ]
    
jobs:
  job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.9

      - name: Run Tests
        run: python manage.py runserver
